/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as LabTestingRouteImport } from './routes/lab-testing'
import { Route as HowToPayRouteImport } from './routes/how-to-pay'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoaArchiveRouteImport } from './routes/coa-archive'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTestingRoute = LabTestingRouteImport.update({
  id: '/lab-testing',
  path: '/lab-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPayRoute = HowToPayRouteImport.update({
  id: '/how-to-pay',
  path: '/how-to-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoaArchiveRoute = CoaArchiveRouteImport.update({
  id: '/coa-archive',
  path: '/coa-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/coa-archive': typeof CoaArchiveRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to-pay': typeof HowToPayRoute
  '/lab-testing': typeof LabTestingRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standards': typeof StandardsRoute
  '/verify': typeof VerifyRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/coa-archive': typeof CoaArchiveRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to-pay': typeof HowToPayRoute
  '/lab-testing': typeof LabTestingRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standards': typeof StandardsRoute
  '/verify': typeof VerifyRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/coa-archive': typeof CoaArchiveRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to-pay': typeof HowToPayRoute
  '/lab-testing': typeof LabTestingRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standards': typeof StandardsRoute
  '/verify': typeof VerifyRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/coa-archive'
    | '/contact'
    | '/faq'
    | '/how-to-pay'
    | '/lab-testing'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/standards'
    | '/verify'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/coa-archive'
    | '/contact'
    | '/faq'
    | '/how-to-pay'
    | '/lab-testing'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/standards'
    | '/verify'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/coa-archive'
    | '/contact'
    | '/faq'
    | '/how-to-pay'
    | '/lab-testing'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/standards'
    | '/verify'
    | '/shop/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CoaArchiveRoute: typeof CoaArchiveRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowToPayRoute: typeof HowToPayRoute
  LabTestingRoute: typeof LabTestingRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StandardsRoute: typeof StandardsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-testing': {
      id: '/lab-testing'
      path: '/lab-testing'
      fullPath: '/lab-testing'
      preLoaderRoute: typeof LabTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-pay': {
      id: '/how-to-pay'
      path: '/how-to-pay'
      fullPath: '/how-to-pay'
      preLoaderRoute: typeof HowToPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coa-archive': {
      id: '/coa-archive'
      path: '/coa-archive'
      fullPath: '/coa-archive'
      preLoaderRoute: typeof CoaArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CoaArchiveRoute: CoaArchiveRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowToPayRoute: HowToPayRoute,
  LabTestingRoute: LabTestingRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StandardsRoute: StandardsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
