/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as ResearchUseRouteImport } from './routes/research-use'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentPolicyRouteImport } from './routes/payment-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowToPayRouteImport } from './routes/how-to-pay'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoaArchiveRouteImport } from './routes/coa-archive'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutOrderNumberRouteImport } from './routes/checkout.$orderNumber'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAccountRouteImport } from './routes/admin.account'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as CheckoutThankYouOrderNumberRouteImport } from './routes/checkout.thank-you.$orderNumber'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiAdminStatsTodayRouteImport } from './routes/api/admin/stats.today'
import { Route as ApiAdminOrdersUnpaidRouteImport } from './routes/api/admin/orders.unpaid'
import { Route as ApiAdminOrdersToshipRouteImport } from './routes/api/admin/orders.toship'
import { Route as ApiAdminOrdersTodayRouteImport } from './routes/api/admin/orders.today'
import { Route as ApiAdminOrdersPendingRouteImport } from './routes/api/admin/orders.pending'
import { Route as ApiAdminOrdersLowstockRouteImport } from './routes/api/admin/orders.lowstock'
import { Route as ApiAdminOrdersOrderNumberRouteImport } from './routes/api/admin/orders.$orderNumber'
import { Route as ApiAdminCustomersEmailRouteImport } from './routes/api/admin/customers.$email'
import { Route as ApiAdminOrdersOrderNumberMarkShippedRouteImport } from './routes/api/admin/orders.$orderNumber.mark-shipped'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchUseRoute = ResearchUseRouteImport.update({
  id: '/research-use',
  path: '/research-use',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPolicyRoute = PaymentPolicyRouteImport.update({
  id: '/payment-policy',
  path: '/payment-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPayRoute = HowToPayRouteImport.update({
  id: '/how-to-pay',
  path: '/how-to-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoaArchiveRoute = CoaArchiveRouteImport.update({
  id: '/coa-archive',
  path: '/coa-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderNumberRoute = CheckoutOrderNumberRouteImport.update({
  id: '/$orderNumber',
  path: '/$orderNumber',
  getParentRoute: () => CheckoutRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutThankYouOrderNumberRoute =
  CheckoutThankYouOrderNumberRouteImport.update({
    id: '/thank-you/$orderNumber',
    path: '/thank-you/$orderNumber',
    getParentRoute: () => CheckoutRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsTodayRoute = ApiAdminStatsTodayRouteImport.update({
  id: '/api/admin/stats/today',
  path: '/api/admin/stats/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersUnpaidRoute = ApiAdminOrdersUnpaidRouteImport.update({
  id: '/api/admin/orders/unpaid',
  path: '/api/admin/orders/unpaid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersToshipRoute = ApiAdminOrdersToshipRouteImport.update({
  id: '/api/admin/orders/toship',
  path: '/api/admin/orders/toship',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersTodayRoute = ApiAdminOrdersTodayRouteImport.update({
  id: '/api/admin/orders/today',
  path: '/api/admin/orders/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersPendingRoute = ApiAdminOrdersPendingRouteImport.update({
  id: '/api/admin/orders/pending',
  path: '/api/admin/orders/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersLowstockRoute = ApiAdminOrdersLowstockRouteImport.update({
  id: '/api/admin/orders/lowstock',
  path: '/api/admin/orders/lowstock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersOrderNumberRoute =
  ApiAdminOrdersOrderNumberRouteImport.update({
    id: '/api/admin/orders/$orderNumber',
    path: '/api/admin/orders/$orderNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminCustomersEmailRoute = ApiAdminCustomersEmailRouteImport.update({
  id: '/api/admin/customers/$email',
  path: '/api/admin/customers/$email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersOrderNumberMarkShippedRoute =
  ApiAdminOrdersOrderNumberMarkShippedRouteImport.update({
    id: '/mark-shipped',
    path: '/mark-shipped',
    getParentRoute: () => ApiAdminOrdersOrderNumberRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/coa-archive': typeof CoaArchiveRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to-pay': typeof HowToPayRoute
  '/login': typeof LoginRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/research-use': typeof ResearchUseRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verification': typeof VerificationRoute
  '/verify': typeof VerifyRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$orderNumber': typeof CheckoutOrderNumberRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/checkout/thank-you/$orderNumber': typeof CheckoutThankYouOrderNumberRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/admin/customers/$email': typeof ApiAdminCustomersEmailRoute
  '/api/admin/orders/$orderNumber': typeof ApiAdminOrdersOrderNumberRouteWithChildren
  '/api/admin/orders/lowstock': typeof ApiAdminOrdersLowstockRoute
  '/api/admin/orders/pending': typeof ApiAdminOrdersPendingRoute
  '/api/admin/orders/today': typeof ApiAdminOrdersTodayRoute
  '/api/admin/orders/toship': typeof ApiAdminOrdersToshipRoute
  '/api/admin/orders/unpaid': typeof ApiAdminOrdersUnpaidRoute
  '/api/admin/stats/today': typeof ApiAdminStatsTodayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/admin/orders/$orderNumber/mark-shipped': typeof ApiAdminOrdersOrderNumberMarkShippedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/coa-archive': typeof CoaArchiveRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to-pay': typeof HowToPayRoute
  '/login': typeof LoginRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/research-use': typeof ResearchUseRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verification': typeof VerificationRoute
  '/verify': typeof VerifyRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$orderNumber': typeof CheckoutOrderNumberRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopIndexRoute
  '/checkout/thank-you/$orderNumber': typeof CheckoutThankYouOrderNumberRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/admin/customers/$email': typeof ApiAdminCustomersEmailRoute
  '/api/admin/orders/$orderNumber': typeof ApiAdminOrdersOrderNumberRouteWithChildren
  '/api/admin/orders/lowstock': typeof ApiAdminOrdersLowstockRoute
  '/api/admin/orders/pending': typeof ApiAdminOrdersPendingRoute
  '/api/admin/orders/today': typeof ApiAdminOrdersTodayRoute
  '/api/admin/orders/toship': typeof ApiAdminOrdersToshipRoute
  '/api/admin/orders/unpaid': typeof ApiAdminOrdersUnpaidRoute
  '/api/admin/stats/today': typeof ApiAdminStatsTodayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/admin/orders/$orderNumber/mark-shipped': typeof ApiAdminOrdersOrderNumberMarkShippedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/coa-archive': typeof CoaArchiveRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to-pay': typeof HowToPayRoute
  '/login': typeof LoginRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/research-use': typeof ResearchUseRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verification': typeof VerificationRoute
  '/verify': typeof VerifyRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$orderNumber': typeof CheckoutOrderNumberRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/checkout/thank-you/$orderNumber': typeof CheckoutThankYouOrderNumberRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/admin/customers/$email': typeof ApiAdminCustomersEmailRoute
  '/api/admin/orders/$orderNumber': typeof ApiAdminOrdersOrderNumberRouteWithChildren
  '/api/admin/orders/lowstock': typeof ApiAdminOrdersLowstockRoute
  '/api/admin/orders/pending': typeof ApiAdminOrdersPendingRoute
  '/api/admin/orders/today': typeof ApiAdminOrdersTodayRoute
  '/api/admin/orders/toship': typeof ApiAdminOrdersToshipRoute
  '/api/admin/orders/unpaid': typeof ApiAdminOrdersUnpaidRoute
  '/api/admin/stats/today': typeof ApiAdminStatsTodayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/admin/orders/$orderNumber/mark-shipped': typeof ApiAdminOrdersOrderNumberMarkShippedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/checkout'
    | '/coa-archive'
    | '/contact'
    | '/faq'
    | '/how-to-pay'
    | '/login'
    | '/payment-policy'
    | '/privacy'
    | '/research-use'
    | '/shipping-returns'
    | '/sitemap.xml'
    | '/standards'
    | '/terms'
    | '/unsubscribe'
    | '/verification'
    | '/verify'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/checkout/$orderNumber'
    | '/email/unsubscribe'
    | '/shop/$slug'
    | '/shop/'
    | '/checkout/thank-you/$orderNumber'
    | '/lovable/email/suppression'
    | '/api/admin/customers/$email'
    | '/api/admin/orders/$orderNumber'
    | '/api/admin/orders/lowstock'
    | '/api/admin/orders/pending'
    | '/api/admin/orders/today'
    | '/api/admin/orders/toship'
    | '/api/admin/orders/unpaid'
    | '/api/admin/stats/today'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/admin/orders/$orderNumber/mark-shipped'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/checkout'
    | '/coa-archive'
    | '/contact'
    | '/faq'
    | '/how-to-pay'
    | '/login'
    | '/payment-policy'
    | '/privacy'
    | '/research-use'
    | '/shipping-returns'
    | '/sitemap.xml'
    | '/standards'
    | '/terms'
    | '/unsubscribe'
    | '/verification'
    | '/verify'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/checkout/$orderNumber'
    | '/email/unsubscribe'
    | '/shop/$slug'
    | '/shop'
    | '/checkout/thank-you/$orderNumber'
    | '/lovable/email/suppression'
    | '/api/admin/customers/$email'
    | '/api/admin/orders/$orderNumber'
    | '/api/admin/orders/lowstock'
    | '/api/admin/orders/pending'
    | '/api/admin/orders/today'
    | '/api/admin/orders/toship'
    | '/api/admin/orders/unpaid'
    | '/api/admin/stats/today'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/admin/orders/$orderNumber/mark-shipped'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/checkout'
    | '/coa-archive'
    | '/contact'
    | '/faq'
    | '/how-to-pay'
    | '/login'
    | '/payment-policy'
    | '/privacy'
    | '/research-use'
    | '/shipping-returns'
    | '/sitemap.xml'
    | '/standards'
    | '/terms'
    | '/unsubscribe'
    | '/verification'
    | '/verify'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/checkout/$orderNumber'
    | '/email/unsubscribe'
    | '/shop/$slug'
    | '/shop/'
    | '/checkout/thank-you/$orderNumber'
    | '/lovable/email/suppression'
    | '/api/admin/customers/$email'
    | '/api/admin/orders/$orderNumber'
    | '/api/admin/orders/lowstock'
    | '/api/admin/orders/pending'
    | '/api/admin/orders/today'
    | '/api/admin/orders/toship'
    | '/api/admin/orders/unpaid'
    | '/api/admin/stats/today'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/admin/orders/$orderNumber/mark-shipped'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CoaArchiveRoute: typeof CoaArchiveRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowToPayRoute: typeof HowToPayRoute
  LoginRoute: typeof LoginRoute
  PaymentPolicyRoute: typeof PaymentPolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  ResearchUseRoute: typeof ResearchUseRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StandardsRoute: typeof StandardsRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerificationRoute: typeof VerificationRoute
  VerifyRoute: typeof VerifyRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiAdminCustomersEmailRoute: typeof ApiAdminCustomersEmailRoute
  ApiAdminOrdersOrderNumberRoute: typeof ApiAdminOrdersOrderNumberRouteWithChildren
  ApiAdminOrdersLowstockRoute: typeof ApiAdminOrdersLowstockRoute
  ApiAdminOrdersPendingRoute: typeof ApiAdminOrdersPendingRoute
  ApiAdminOrdersTodayRoute: typeof ApiAdminOrdersTodayRoute
  ApiAdminOrdersToshipRoute: typeof ApiAdminOrdersToshipRoute
  ApiAdminOrdersUnpaidRoute: typeof ApiAdminOrdersUnpaidRoute
  ApiAdminStatsTodayRoute: typeof ApiAdminStatsTodayRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-use': {
      id: '/research-use'
      path: '/research-use'
      fullPath: '/research-use'
      preLoaderRoute: typeof ResearchUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-policy': {
      id: '/payment-policy'
      path: '/payment-policy'
      fullPath: '/payment-policy'
      preLoaderRoute: typeof PaymentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-pay': {
      id: '/how-to-pay'
      path: '/how-to-pay'
      fullPath: '/how-to-pay'
      preLoaderRoute: typeof HowToPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coa-archive': {
      id: '/coa-archive'
      path: '/coa-archive'
      fullPath: '/coa-archive'
      preLoaderRoute: typeof CoaArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderNumber': {
      id: '/checkout/$orderNumber'
      path: '/$orderNumber'
      fullPath: '/checkout/$orderNumber'
      preLoaderRoute: typeof CheckoutOrderNumberRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/thank-you/$orderNumber': {
      id: '/checkout/thank-you/$orderNumber'
      path: '/thank-you/$orderNumber'
      fullPath: '/checkout/thank-you/$orderNumber'
      preLoaderRoute: typeof CheckoutThankYouOrderNumberRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats/today': {
      id: '/api/admin/stats/today'
      path: '/api/admin/stats/today'
      fullPath: '/api/admin/stats/today'
      preLoaderRoute: typeof ApiAdminStatsTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/unpaid': {
      id: '/api/admin/orders/unpaid'
      path: '/api/admin/orders/unpaid'
      fullPath: '/api/admin/orders/unpaid'
      preLoaderRoute: typeof ApiAdminOrdersUnpaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/toship': {
      id: '/api/admin/orders/toship'
      path: '/api/admin/orders/toship'
      fullPath: '/api/admin/orders/toship'
      preLoaderRoute: typeof ApiAdminOrdersToshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/today': {
      id: '/api/admin/orders/today'
      path: '/api/admin/orders/today'
      fullPath: '/api/admin/orders/today'
      preLoaderRoute: typeof ApiAdminOrdersTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/pending': {
      id: '/api/admin/orders/pending'
      path: '/api/admin/orders/pending'
      fullPath: '/api/admin/orders/pending'
      preLoaderRoute: typeof ApiAdminOrdersPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/lowstock': {
      id: '/api/admin/orders/lowstock'
      path: '/api/admin/orders/lowstock'
      fullPath: '/api/admin/orders/lowstock'
      preLoaderRoute: typeof ApiAdminOrdersLowstockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/$orderNumber': {
      id: '/api/admin/orders/$orderNumber'
      path: '/api/admin/orders/$orderNumber'
      fullPath: '/api/admin/orders/$orderNumber'
      preLoaderRoute: typeof ApiAdminOrdersOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/customers/$email': {
      id: '/api/admin/customers/$email'
      path: '/api/admin/customers/$email'
      fullPath: '/api/admin/customers/$email'
      preLoaderRoute: typeof ApiAdminCustomersEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/$orderNumber/mark-shipped': {
      id: '/api/admin/orders/$orderNumber/mark-shipped'
      path: '/mark-shipped'
      fullPath: '/api/admin/orders/$orderNumber/mark-shipped'
      preLoaderRoute: typeof ApiAdminOrdersOrderNumberMarkShippedRouteImport
      parentRoute: typeof ApiAdminOrdersOrderNumberRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CheckoutRouteChildren {
  CheckoutOrderNumberRoute: typeof CheckoutOrderNumberRoute
  CheckoutThankYouOrderNumberRoute: typeof CheckoutThankYouOrderNumberRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutOrderNumberRoute: CheckoutOrderNumberRoute,
  CheckoutThankYouOrderNumberRoute: CheckoutThankYouOrderNumberRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ApiAdminOrdersOrderNumberRouteChildren {
  ApiAdminOrdersOrderNumberMarkShippedRoute: typeof ApiAdminOrdersOrderNumberMarkShippedRoute
}

const ApiAdminOrdersOrderNumberRouteChildren: ApiAdminOrdersOrderNumberRouteChildren =
  {
    ApiAdminOrdersOrderNumberMarkShippedRoute:
      ApiAdminOrdersOrderNumberMarkShippedRoute,
  }

const ApiAdminOrdersOrderNumberRouteWithChildren =
  ApiAdminOrdersOrderNumberRoute._addFileChildren(
    ApiAdminOrdersOrderNumberRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  CoaArchiveRoute: CoaArchiveRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowToPayRoute: HowToPayRoute,
  LoginRoute: LoginRoute,
  PaymentPolicyRoute: PaymentPolicyRoute,
  PrivacyRoute: PrivacyRoute,
  ResearchUseRoute: ResearchUseRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StandardsRoute: StandardsRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerificationRoute: VerificationRoute,
  VerifyRoute: VerifyRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiAdminCustomersEmailRoute: ApiAdminCustomersEmailRoute,
  ApiAdminOrdersOrderNumberRoute: ApiAdminOrdersOrderNumberRouteWithChildren,
  ApiAdminOrdersLowstockRoute: ApiAdminOrdersLowstockRoute,
  ApiAdminOrdersPendingRoute: ApiAdminOrdersPendingRoute,
  ApiAdminOrdersTodayRoute: ApiAdminOrdersTodayRoute,
  ApiAdminOrdersToshipRoute: ApiAdminOrdersToshipRoute,
  ApiAdminOrdersUnpaidRoute: ApiAdminOrdersUnpaidRoute,
  ApiAdminStatsTodayRoute: ApiAdminStatsTodayRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
