-- 1. Add columns needed to represent the public catalog faithfully
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS dosage text,
  ADD COLUMN IF NOT EXISTS size_label text;

-- 2. Seed products from the public catalog. Idempotent via ON CONFLICT (slug).
INSERT INTO public.products (
  slug, name, category, dosage, size_label, price_usd, purity, endotoxin,
  lot_number, stock_status, status, featured, lyophilized,
  short_description, full_description, molecular_class, storage_guidance,
  inventory_count, low_stock_threshold, sort_order
) VALUES
  ('bpc-157-12mg','BPC-157 12mg VIAL','Tissue Recovery','12MG','12 mg vial',95,'99.4%','< 0.5 EU/mg','PP-2612','in_stock','published',true,true,
   'Body Protection Compound, 12 mg lyophilized.',
   'A 15-amino acid synthetic peptide studied in research models for tissue repair and gastrointestinal protective pathways. Released only after independent HPLC and ESI-MS verification.',
   '15-amino acid synthetic peptide','Store sealed vials at –20 °C, protected from light.',50,5,0),
  ('bpc-tb-500-blend','BPC-157 / TB-500 10mg/10mg VIAL','Tissue Recovery','10MG / 10MG','10 mg / 10 mg vial',175,'99.2%','< 0.5 EU/mg','PP-2611','in_stock','published',true,true,
   'Combined BPC-157 + TB-500 lyophilized blend.',
   'A pre-formulated lyophilized combination of BPC-157 and TB-500 supplied in a single nitrogen-sealed research vial. Each lot is verified for identity and purity by an independent ISO 17025 laboratory.',
   'Dual-compound recovery blend','Store sealed vials at –20 °C, protected from light.',40,5,1),
  ('tb-500-fragment-12mg','TB-500 12mg VIAL','Tissue Recovery','12MG','12 mg vial',120,'99.1%','< 0.5 EU/mg','PP-2610','in_stock','published',false,true,
   'Active fragment of Thymosin Beta-4.',
   'The synthetic active fragment of Thymosin Beta-4 commonly referenced as TB-500. Manufactured under cGMP and released under independent HPLC and ESI-MS verification.',
   'Thymosin Beta-4 active fragment','Store sealed vials at –20 °C, protected from light.',45,5,2),
  ('tb-4-full-sequence-10mg','TB-4 (Full Sequence) 10mg VIAL','Tissue Recovery','10MG','10 mg vial',155,'99.0%','< 0.5 EU/mg','PP-2609','in_stock','published',false,true,
   'Full 43-amino acid Thymosin Beta-4.',
   'The complete 43-amino acid Thymosin Beta-4 polypeptide, supplied lyophilized for in-vitro tissue-recovery and cellular research.',
   'Thymosin Beta-4 full 43-aa sequence','Store sealed vials at –20 °C, protected from light.',30,5,3),
  ('ghk-cu-100mg','GHK-CU 100mg VIAL','Regenerative','100MG','100 mg vial',95,'99.6%','< 0.5 EU/mg','PP-2608','in_stock','published',true,true,
   'Copper tripeptide, 100 mg research format.',
   'A naturally occurring copper-binding tripeptide investigated for extracellular matrix remodeling and regenerative pathways. Lyophilized, nitrogen-sealed.',
   'Copper-binding tripeptide','Store sealed vials at –20 °C, protected from light.',60,5,4),
  ('ghk-cu-50mg','GHK-CU 50mg VIAL','Regenerative','50MG','50 mg vial',65,'99.6%','< 0.5 EU/mg','PP-2607','in_stock','published',false,true,
   'Copper tripeptide, 50 mg research format.',
   'Half-format research vial of GHK-Cu for shorter studies. Independently verified for identity, copper coordination, and HPLC purity.',
   'Copper-binding tripeptide','Store sealed vials at –20 °C, protected from light.',60,5,5),
  ('glow-70','Glow 70 VIAL','Regenerative','70MG','70 mg vial',180,'99.2%','< 0.5 EU/mg','PP-2606','in_stock','published',true,true,
   'Tri-compound regenerative research blend.',
   'A combined lyophilized research formulation supplied as a single nitrogen-sealed vial for combination-protocol studies in regenerative and dermal pathways.',
   'Tri-compound regenerative blend','Store sealed vials at –20 °C, protected from light.',25,5,6),
  ('ghrp-6-10mg','GHRP-6 10mg VIAL','Growth Hormone','10MG','10 mg vial',60,'99.3%','< 0.5 EU/mg','PP-2605','in_stock','published',false,true,
   'Growth-hormone-releasing hexapeptide.',
   'A synthetic hexapeptide investigated in growth-hormone signaling and appetite-regulation research. Lyophilized and lot-verified.',
   'GH-releasing hexapeptide','Store sealed vials at –20 °C, protected from light.',55,5,7),
  ('ipamorelin-10mg','Ipamorelin 10mg VIAL','Growth Hormone','10MG','10 mg vial',75,'99.5%','< 0.5 EU/mg','PP-2604','in_stock','published',true,true,
   'Selective GH-releasing pentapeptide.',
   'A selective synthetic pentapeptide studied in growth-hormone signaling research. Sealed vials with sterile rubber stopper and aluminum crimp.',
   'Selective GH-releasing pentapeptide','Store sealed vials at –20 °C, protected from light.',50,5,8),
  ('hcg-10000-iu','HCG 10,000 IU VIAL','Hormonal','10,000 IU','10,000 IU vial',180,'99.0%','< 0.5 EU/mg','PP-2603','in_stock','published',false,true,
   'Glycoprotein hormone, 10,000 IU format.',
   'Lyophilized human chorionic gonadotropin supplied for in-vitro endocrine research. Released only after independent identity and potency verification.',
   'Human chorionic gonadotropin','Store sealed vials at –20 °C, protected from light.',35,5,9),
  ('hcg-5000-iu','HCG 5,000 IU VIAL','Hormonal','5,000 IU','5,000 IU vial',100,'99.0%','< 0.5 EU/mg','PP-2602','in_stock','published',false,true,
   'Glycoprotein hormone, 5,000 IU format.',
   'Smaller-format research vial of lyophilized HCG. Each lot is independently verified for identity and supplied with a signed certificate of analysis.',
   'Human chorionic gonadotropin','Store sealed vials at –20 °C, protected from light.',40,5,10),
  ('melanotan-2-10mg','Melanotan-2 10mg VIAL','Pigmentation','10MG','10 mg vial',60,'99.1%','< 0.5 EU/mg','PP-2601','in_stock','published',false,true,
   'Cyclic α-MSH analogue, lyophilized.',
   'A synthetic cyclic analogue of the peptide hormone α-MSH supplied for in-vitro melanocortin-receptor research.',
   'Cyclic α-MSH analogue','Store sealed vials at –20 °C, protected from light.',45,5,11),
  ('mots-c-10mg','MOTS-C 10mg VIAL','Mitochondrial','10MG','10 mg vial',130,'99.1%','< 0.5 EU/mg','PP-2600','in_stock','published',false,true,
   'Mitochondrial signaling peptide.',
   'A 16-amino acid peptide encoded within the mitochondrial genome, studied for metabolic homeostasis and aging-pathway research.',
   'Mitochondrial-derived peptide','Store sealed vials at –20 °C, protected from light.',30,5,12),
  ('ss-31-10mg','SS-31 10mg VIAL','Mitochondrial','10MG','10 mg vial',150,'99.2%','< 0.5 EU/mg','PP-2599','in_stock','published',false,true,
   'Cardiolipin-targeted tetrapeptide.',
   'A mitochondria-targeted aromatic-cationic tetrapeptide that selectively associates with cardiolipin, studied in inner-membrane stability and bioenergetic research.',
   'Mitochondria-targeted tetrapeptide','Store sealed vials at –20 °C, protected from light.',25,5,13),
  ('retatrutide-12mg','Retatrutide 12mg VIAL','Metabolic','12MG','12 mg vial',165,'99.3%','< 0.5 EU/mg','PP-2598','in_stock','published',true,true,
   'Triple-agonist metabolic analogue.',
   'A research-grade triple-receptor agonist (GLP-1 / GIP / glucagon) supplied for in-vitro studies in incretin signaling and glucose homeostasis.',
   'GLP-1 / GIP / glucagon triple-agonist','Store sealed vials at –20 °C, protected from light.',40,5,14),
  ('retatrutide-30mg','Retatrutide 30mg VIAL','Metabolic','30MG','30 mg vial',360,'99.3%','< 0.5 EU/mg','PP-2597','in_stock','published',false,true,
   'Extended-format triple-agonist vial.',
   'Larger-format research vial of Retatrutide for extended in-vitro metabolic-pathway protocols. Each lot is independently HPLC and mass-spec verified.',
   'GLP-1 / GIP / glucagon triple-agonist','Store sealed vials at –20 °C, protected from light.',20,5,15),
  ('retatrutide-60mg','Retatrutide 60mg VIAL','Metabolic','60MG','60 mg vial',680,'99.3%','< 0.5 EU/mg','PP-2596','out_of_stock','published',false,true,
   'Bulk research format triple-agonist vial.',
   'Bulk-format research vial of Retatrutide. Supplied under nitrogen seal with full lot documentation and independent verification.',
   'GLP-1 / GIP / glucagon triple-agonist','Store sealed vials at –20 °C, protected from light.',0,5,16),
  ('semaglutide-5mg','Semaglutide 5mg VIAL','Metabolic','5MG','5 mg vial',110,'99.3%','< 0.5 EU/mg','PP-2595','in_stock','published',true,true,
   'GLP-1 receptor analogue, 5 mg format.',
   'Research-grade semaglutide supplied as a lyophilized cake for in-vitro studies in GLP-1 receptor signaling.',
   'GLP-1 receptor analogue','Store sealed vials at –20 °C, protected from light.',50,5,17),
  ('semaglutide-10mg','Semaglutide 10mg VIAL','Metabolic','10MG','10 mg vial',195,'99.3%','< 0.5 EU/mg','PP-2594','in_stock','published',false,true,
   'GLP-1 receptor analogue, 10 mg format.',
   'Extended-format research vial of semaglutide for longer-duration in-vitro incretin-pathway studies.',
   'GLP-1 receptor analogue','Store sealed vials at –20 °C, protected from light.',35,5,18),
  ('tirzepatide-10mg','Tirzepatide 10mg VIAL','Metabolic','10MG','10 mg vial',175,'99.2%','< 0.5 EU/mg','PP-2593','in_stock','published',true,true,
   'Dual incretin receptor analogue.',
   'A research-grade GIP / GLP-1 dual-agonist supplied for in-vitro incretin and glucose-homeostasis research. Released after independent verification.',
   'GIP / GLP-1 dual-agonist analogue','Store sealed vials at –20 °C, protected from light.',45,5,19),
  ('tirzepatide-30mg','Tirzepatide 30mg VIAL','Metabolic','30MG','30 mg vial',460,'99.2%','< 0.5 EU/mg','PP-2592','in_stock','published',false,true,
   'Extended-format dual-agonist vial.',
   'Larger-format research vial of tirzepatide. Supplied lyophilized under nitrogen with a signed independent certificate of analysis.',
   'GIP / GLP-1 dual-agonist analogue','Store sealed vials at –20 °C, protected from light.',25,5,20)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  dosage = EXCLUDED.dosage,
  size_label = EXCLUDED.size_label,
  price_usd = EXCLUDED.price_usd,
  purity = EXCLUDED.purity,
  endotoxin = EXCLUDED.endotoxin,
  lot_number = EXCLUDED.lot_number,
  stock_status = EXCLUDED.stock_status,
  status = EXCLUDED.status,
  featured = EXCLUDED.featured,
  lyophilized = EXCLUDED.lyophilized,
  short_description = EXCLUDED.short_description,
  full_description = EXCLUDED.full_description,
  molecular_class = EXCLUDED.molecular_class,
  storage_guidance = EXCLUDED.storage_guidance,
  inventory_count = EXCLUDED.inventory_count,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

-- 3. Seed product_lots from the seeded products. Dates step backwards from 2026-05-12 in the same order as sort_order so the archive timeline matches the static data.
INSERT INTO public.product_lots (
  product_id, lot_number, purity, identity_status, identity_method,
  endotoxin, water_content, release_date, best_before,
  tested_by, lab_partner, active
)
SELECT
  p.id,
  p.lot_number,
  p.purity,
  'Confirmed',
  'RP-HPLC / ESI-MS',
  '< 0.5 EU/mg',
  '1.8%',
  (DATE '2026-05-12' - (p.sort_order * 4))::date,
  (DATE '2026-05-12' - (p.sort_order * 4) + INTERVAL '2 years')::date,
  'Northbridge Analytical',
  'Northbridge Analytical (ISO/IEC 17025:2017)',
  (p.stock_status = 'in_stock')
FROM public.products p
WHERE p.lot_number IS NOT NULL
ON CONFLICT DO NOTHING;